### PR TITLE
Created a layout for detail page for each job post

### PR DESCRIPTION
**Pull request by jhay-25**

### CODE REVIEW

**Comment by jhay-25** [comment]
Desktop view: 
Screenshot (76)
Mobile view:
Screenshot (78)

**Review by RostykL — APPROVED** [review]
components/DetailsSideBar/svg.js - new ArrowIcon component -> returns svg
public/ - I can find here the save svg image
You can put all images in the public folder and then just write src='/svg_name', / - means look it public folder(nextjs feature)

**Comment by jhay-25** [comment]
> public/ - I can find here the save svg image

Okay, I'll move the svg in there. The reason I'm putting the svg file in the public folder despite the fact that I'm not using it, so you can see the original file.

**Comment by jhay-25** [comment]
> components/DetailsSideBar/svg.js - new ArrowIcon component -> returns svg
> You can put all images in the public folder and then just write src='/svg_name', / - means look it public folder(nextjs feature)

You mean to use it as an image? But I won't be able to control its color through css, right? Also I made the icon (arrow) as a component so the component (Sidebar) that would be using it won't get clunky

**Pull request merged**
